# Generated by Django 5.1.2 on 2024-10-25 21:04

import app.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_1', models.CharField(max_length=255)),
                ('street_2', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('zip', models.CharField(max_length=255)),
            ],
            bases=(app.models.TimestampsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='BusinessCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('chamber_of_commerce_id', models.CharField(db_index=True, max_length=255, unique=True)),
            ],
            bases=(app.models.TimestampsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('contacts', models.JSONField(blank=True, default=list)),
                ('phone_numbers', models.JSONField(blank=True, default=list)),
                ('chamber_of_commerce_id', models.CharField(db_index=True, max_length=255, null=True, unique=True)),
                ('website_url', models.URLField(null=True)),
                ('google_maps_url', models.URLField(null=True)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.address')),
                ('categories', models.ManyToManyField(to='app.businesscategory')),
            ],
            bases=(app.models.TimestampsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SocialMediaLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.business')),
            ],
        ),
    ]
